### ISSUE TITLE
Missing IP addresses during import

### ISSUE THREAD

**Issue by Emod94** [credativ/icingaweb2-module-azure#3]
Hello everybody,

I've been using your module for a few days now and I'm really happy!
My problem is that some VM's don't get IP addresses.
During the import job no IP addresses of the virtual machines are recognized.

My IP addresses are assigned dynamically. The virtual machines are
is enabled and the application has been granted read permissions in Azure to the subscription
authorized.

Do you have a tip for me?

**Comment by archandha** [comment]
Hi,
please provide us with some more information: 

- specify what kind of “dynamically” assigned IP addresses you use
- do your VM have multiple network interfaces or
- do your network interfaces have multiple ip address sets assigned?
- do you use scale sets?

For your information: 
- scale sets are not implemented as the time of writing
- with multiple a ip address sets assigned to an interface, only the first set is evaluated
- with multiple network interfaces, the last with an IP address wins and overwrites the others

This is due the fact that we needed one IP address for the director to use and we had a to implement a simple decision logic to get this one address. This decision needs to be done somehow. Another approach would be to list all addresses available but this was beyond scope of the project this tool was raised in. 


The decision is done in a "foreach" loop in https://github.com/credativ/icingaweb2-module-azure/blob/master/library/Azure/VirtualMachines.php

line 126 and on.


Kind regards
Peter

**Comment by Emod94** [comment]
Hi @archandha,

- **specify what kind of “dynamically” assigned IP addresses you use**
Azure dynamically assigns the IP address to the virtual machine via Azure DHCP

- **do your VM have multiple network interfaces or**
No Only one network interface per VM is used. If I enter the network interfaces as import source in the Director, I even get the network interfaces and the corresponding fields. However, the values vmName are missing when importing the network interfaces. It seems to me that there is a problem with the link between the network interface and the virtual machine.

- **do your network interfaces have multiple ip address sets assigned?**
No, only one IP address per interface

- **do you use scale sets?**
No Scale Sets are not used

I think we misunderstood each other a little. I always get back the value "NULL" by importing the privateIP. On the authorization side, the problem cannot occur on Azure (had already tried several authorization levels here). I suspect there is a problem in Azure with the connection between the network interfaces and the virtual machine. I get an IP address back for a handful of systems and only the value "Null" for a large number of systems.

Greetings,
Dominik

**Comment by archandha** [comment]
Hi, @Emod94 

ok, I will take a look into this. I assume I'll add some more logging, so that you could see, whats happening. Hopefully, this will help to nail this down. 

Cheers
Peter

**Comment by archandha** [comment]
Hi @Emod94 
I just pushed a small update that should help investigating this. Please have the log level set to at least level "info" and take a look into your logs. If there is an interface without a VM id, it should occur in the logs. Please let me know if something pops up in the logs.

Cheers, Peter

**Comment by archandha** [comment]
Hi, @Emod94
any news on this?

Cheers,
Peter

**Comment by archandha** [comment]
After a 11 months without response, I consider this solved ;-)
