### ISSUE TITLE
Import virtual machine: tags and status will not be imported

### ISSUE THREAD

**Issue by Mordecaine** [credativ/icingaweb2-module-azure#4]
Hello,

is it possible to import the status of the virtual machine (running, stopped etc.)?
Further more it would be nice to import the tags of a virtual machine or a different object.

Cheers, Mordecaine

**Comment by Mordecaine** [comment]
Hello,

I tried my best to implement the features I asked for.
It works, but someone who is able to write proper code in PHP should check it.

I will do a pull request.

Cheers Mordecaine

**Comment by archandha** [comment]
Hi, 
your PR https://github.com/credativ/icingaweb2-module-azure/pull/5 was merged. I did some reformatting but it should be working. Thank you very much!
Cheers
